spring:
  application:
    name: backend

  # DB-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mini_mings?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: mings
    password: 1234

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: me.minimings.backend.model
  # camel -> snake
  configuration:
    map-underscore-to-camel-case: true
    # performance improvement
    default-fetch-size: 100
    default-executor-type: REUSE

jwt:
  header: Authorization
  # The secret key must be 512 bits (at least 64 bytes) in size because the HS512 algorithm is used.
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  # Token validity period
  token-validity-in-seconds: 86400
