spring:
  application:
    name: backend

  # DB-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mini_mings?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: mings
    password: 1234

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.mings.auth.model
  # snake -> camel
  configuration:
    map-underscore-to-camel-case: true
    # performance improvement
    default-fetch-size: 100
    default-executor-type: REUSE
